using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GymNotebook.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddPrivacyAccountIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "acknowledged_privacy_notice_version",
                table: "users",
                type: "character varying(64)",
                maxLength: 64,
                nullable: true);

            // Hand-edited: EF generated defaultValue: Guid.Empty, which would give every
            // existing user the same all-zero id and fail the unique index below. Instead,
            // backfill with gen_random_uuid() (built into PostgreSQL 13+). A volatile default
            // on ADD COLUMN is evaluated once per existing row, so each account gets its own
            // genuine UUID (data-model.md → Transactions and migration validation, step 1).
            migrationBuilder.AddColumn<Guid>(
                name: "privacy_account_id",
                table: "users",
                type: "uuid",
                nullable: false,
                defaultValueSql: "gen_random_uuid()");

            // Then drop the default again, so the model stays "generated by the register
            // handler" and an INSERT that forgets the column fails instead of silently
            // getting a database-made id. Acknowledgement is never seeded: the two
            // acknowledgement columns stay null for every existing user.
            migrationBuilder.Sql("ALTER TABLE users ALTER COLUMN privacy_account_id DROP DEFAULT;");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "privacy_notice_acknowledged_at",
                table: "users",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "sign_in_suspended_at",
                table: "users",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_users_privacy_account_id",
                table: "users",
                column: "privacy_account_id",
                unique: true);

            migrationBuilder.AddCheckConstraint(
                name: "ck_users_privacy_notice_acknowledgement_pair",
                table: "users",
                sql: "(acknowledged_privacy_notice_version IS NULL) = (privacy_notice_acknowledged_at IS NULL)");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_users_privacy_account_id",
                table: "users");

            migrationBuilder.DropCheckConstraint(
                name: "ck_users_privacy_notice_acknowledgement_pair",
                table: "users");

            migrationBuilder.DropColumn(
                name: "acknowledged_privacy_notice_version",
                table: "users");

            migrationBuilder.DropColumn(
                name: "privacy_account_id",
                table: "users");

            migrationBuilder.DropColumn(
                name: "privacy_notice_acknowledged_at",
                table: "users");

            migrationBuilder.DropColumn(
                name: "sign_in_suspended_at",
                table: "users");
        }
    }
}
